# Generated by Django 3.2.18 on 2023-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('count', models.IntegerField(max_length=64, verbose_name='人口数')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=64, verbose_name='订单号'),
        ),
    ]
